[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mon_projet"
version = "0.1.0"
description = "Description du projet."
authors = [
  { name="Votre Nom", email="votre@email.com" }
]
